[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/kayabaNerve/crypto-bigint?branch=c-repr"]
git = "https://github.com/kayabaNerve/crypto-bigint"
branch = "c-repr"
replace-with = "vendored-sources"

[source."git+https://github.com/j-berman/monero-oxide?rev=3867d1bc1b4798b719314ce3b10dc6966b138c8f"]
git = "https://github.com/j-berman/monero-oxide"
rev = "3867d1bc1b4798b719314ce3b10dc6966b138c8f"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "/rust/vendor"
